---
- hosts: all
  become: yes
  roles:
    - node_exporter_setup
    - nginx_setup

- hosts: prometheus
  become: yes
  roles:
    - prometheus_setup
    - alertmanager_setup

- hosts: grafana
  become: yes
  roles:
    - grafana_setup
