
- name: Create NodeExporter group
  group:
    name: node_exporter
    state: present

- name: Lets create NodeExporter user
  user:
    name: node_exporter
    shell: /bin/false
    system: yes

- name: Unarchive a Prometheus that needs to be downloaded(Prometheus archive)
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v1.8.2/node_exporter-1.8.2.linux-amd64.tar.gz"
    dest: "/tmp/"
    remote_src: yes
    extra_opts: [--strip-components=1]   

- name: Move Prometheus binary to /usr/local/bin
  copy:
    src: "/tmp/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    remote_src: yes
    mode: '0755'  # Ensure the binary is executable 

- name: Copy NodeExporter service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: "0755"

- name: Set ownership of Prometheus binary
  file:
    path: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter

    
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
 
- name: Start node_exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes