    - name: Create Prometheus group
      group:
        name: prometheus
        state: present
 
    - name: Add prometheus user
      user:
        name: prometheus
        shell: /bin/false
        system: yes
 
    - name: Unarchive a file that needs to be downloaded(Prometheus archive)
      ansible.builtin.unarchive:
        src: "https://github.com/prometheus/prometheus/releases/download/v2.53.0/prometheus-2.53.0.linux-amd64.tar.gz"
        dest: "/tmp/"
        remote_src: yes
        extra_opts: [--strip-components=1]    
 
    - name: Move Prometheus binary to /usr/local/bin
      copy:
        src: "/tmp/prometheus"
        dest: "/usr/local/bin/prometheus"
        remote_src: yes
        mode: '0755'  # Ensure the binary is executable 
    
    - name: Move Prometheus binary to /usr/local/bin
      copy:
        src: "/tmp/promtool"
        dest: "/usr/local/bin/promtool"
        remote_src: yes
        mode: '0755'  # Ensure the binary is executable       
 
    - name: Create configuration directory
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
      loop:
        - "/etc/prometheus"
        - "/etc/prometheus/data"
    
    - name: Copy Prometheus configuration file
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: "0744"
        
    - name: Copy Prometheus service file
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        owner: prometheus
        group: prometheus
        mode: "0744"         
   
 
    - name: Set ownership of Prometheus binary
      file:
        path: /usr/local/bin/prometheus
        owner: prometheus
        group: prometheus
 
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
 
    - name: Start Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes
 
